### ISSUE TITLE
crash when pasting

### ISSUE THREAD

**Issue by AaronDavidNewman** [AaronDavidNewman/Smoosic#18]
{
 "message": "Uncaught TypeError: Cannot read property 'x' of undefined",
 "stack": "TypeError: Cannot read property 'x' of undefined\n    at Function.adjustScroll (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/common/svgHelpers.js:402:41)\n    at file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/tracker.js:532:45\n    at Array.forEach (<anonymous>)\n    at file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/tracker.js:515:25\n    at Array.forEach (<anonymous>)\n    at suiTracker.mapMeasure (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/tracker.js:513:24)\n    at suiScoreLayout._layoutMeasure (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/scoreLayout.js:454:32)\n    at suiScoreLayout._layoutColumn (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/scoreLayout.js:232:22)\n    at suiScoreLayout._layoutSystem (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/scoreLayout.js:264:19)\n    at suiScoreLayout.layout (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/render/sui/scoreLayout.js:507:18)",
 "lastOperation": "measure backup for undotDuration",
 "scoreString": "Could not serialize score. Cannot read property 'serialize' of undefined"
}

**Comment by AaronDavidNewman** [comment]
This is an intermittent issue, possibly addressed.  Closing until I can get more information.
