### ISSUE TITLE
exception in copy/paste

### ISSUE THREAD

**Issue by AaronDavidNewman** [AaronDavidNewman/Smoosic#2]
Copied 5 notes, paste to beat 2.  crash

{
 "message": "Uncaught TypeError: Cannot read property 'notes' of undefined",
 "stack": "TypeError: Cannot read property 'notes' of undefined\n    at PasteBuffer.pasteSelections (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/smo/xform/copypaste.js:315:20)\n    at Function.pasteBuffer (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/smo/xform/undo.js:238:21)\n    at suiEditor.paste (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/ui/editor.js:76:15)\n    at suiController.handleKeydown (file:///C:/Users/Daddy/Documents/GitHub/VexflowEditor/src/ui/controller.js:269:40)",
 "lastOperation": "measure backup for paste",
 "scoreString": {
  "score": {
   "staffX": 30,
   "staffY": 40,
   "staffWidth": 1600,
   "startIndex": 0,
   "interGap": 30,
   "renumberingMap": {}
  },
  "staves": [
   {
    "staffX": 10,
    "staffY": 40,
    "adjY": 0,
    "staffWidth": 1600,
    "staffHeight": 90,
    "startIndex": 0,
    "renumberingMap": {},
    "keySignatureMap": {},
    "instrumentInfo": {
     "instrumentName": "Treble Instrument",
     "keyOffset": "0",
     "clef": "treble"
    },
    "modifiers": [],
    "measures": [
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 0,
       "measureIndex": 0,
       "systemIndex": 0
      },
      "staffWidth": 200.0000457763672,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": 0,
      "adjX": 3.0000076293945312,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "a",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1002",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1003",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "c",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1004",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "d",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1005",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 1,
       "measureIndex": 1,
       "systemIndex": 1
      },
      "staffWidth": 200,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": 0,
      "adjX": 2.999969482421875,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "e",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4796",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4797",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "a",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4798",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4799",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 2,
       "measureIndex": 2,
       "systemIndex": 2
      },
      "staffWidth": 200.00006103515625,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": 0,
      "adjX": 2.999969482421875,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "c",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4800",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "d",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4801",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "e",
            "accidental": "n",
            "octave": 5
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4802",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto4803",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 3,
       "measureIndex": 3,
       "systemIndex": 3
      },
      "staffWidth": 200,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": 0,
      "adjX": 3,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1017",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1018",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1019",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1020",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 4,
       "measureIndex": 4,
       "systemIndex": 4
      },
      "staffWidth": 200.0001220703125,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": 0,
      "adjX": 3.00006103515625,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1022",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1023",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1024",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1025",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     }
    ]
   },
   {
    "staffX": 10,
    "staffY": 40,
    "adjY": 0,
    "staffWidth": 1600,
    "staffHeight": 90,
    "startIndex": 0,
    "renumberingMap": {},
    "keySignatureMap": {},
    "instrumentInfo": {
     "instrumentName": "Treble Instrument",
     "keyOffset": "0",
     "clef": "treble"
    },
    "modifiers": [],
    "measures": [
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 0,
       "measureIndex": 0,
       "systemIndex": 0
      },
      "staffWidth": 200.0000457763672,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": "0",
      "adjX": 3.0000343322753906,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1027",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1028",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1029",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1030",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 1,
       "measureIndex": 1,
       "systemIndex": 1
      },
      "staffWidth": 200,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": "0",
      "adjX": 2.999969482421875,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1032",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1033",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1034",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1035",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 2,
       "measureIndex": 2,
       "systemIndex": 2
      },
      "staffWidth": 200.00009155273438,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": "0",
      "adjX": 2.999908447265625,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1037",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1038",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1039",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1040",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 3,
       "measureIndex": 3,
       "systemIndex": 3
      },
      "staffWidth": 200,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": "0",
      "adjX": 3,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1042",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1043",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1044",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1045",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     },
     {
      "timeSignature": "4/4",
      "keySignature": "C",
      "staffX": 10,
      "staffY": 40,
      "customModifiers": [],
      "measureNumber": {
       "measureNumber": 4,
       "measureIndex": 4,
       "systemIndex": 4
      },
      "staffWidth": 200.0001220703125,
      "modifierOptions": {},
      "activeVoice": 0,
      "clef": "treble",
      "transposeIndex": "0",
      "adjX": 3.00006103515625,
      "rightMargin": 2,
      "tuplets": [],
      "beamGroups": [],
      "voices": [
       {
        "notes": [
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1047",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1048",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1049",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         },
         {
          "ticks": {
           "numerator": 4096,
           "denominator": 1,
           "remainder": 0
          },
          "pitches": [
           {
            "letter": "b",
            "accidental": "n",
            "octave": 4
           }
          ],
          "noteType": "n",
          "attrs": {
           "id": "auto1050",
           "type": "SmoNote"
          },
          "clef": "treble",
          "endBeam": false,
          "noteModifiers": []
         }
        ]
       }
      ]
     }
    ]
   }
  ]
 }
}

**Comment by AaronDavidNewman** [comment]
Fixed at some point over last 2 months
